'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useExperience,type Modal} from './experience-context';
import {Art,Badge,Button,Icon} from './ui';
import {initialPresentation,initialJourney,money,totals,type Product,type Journey} from '../lib/presentation';
export function Dialogs({value,close}:{value:Modal;close:()=>void}){return value?<DialogContent key={value.kind+value.id} value={value} close={close}/>:null;}
function DialogContent({value,close}:{value:NonNullable<Modal>;close:()=>void}){
 const {state,setState,product,act,go,switchRole,modal,toast,t}=useExperience();const p=product(value.id??'tv'),j=state.journeys[p.id],n=totals(p,j);const kind=value.kind;
 const ref=useRef<HTMLDialogElement>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [qty,setQty]=useState(String(j.qty/p.scale));const [date,setDate]=useState(j.needBy);const [address,setAddress]=useState(j.address);const [method,setMethod]=useState<'UPI'|'Card'>('UPI');const [plan,setPlan]=useState<'full'|'handover'>(j.plan);const [amount,setAmount]=useState(String((kind==='pricing'?j.buyerPrice:j.sellerBid)/100));const [capacity,setCapacity]=useState(String(j.capacity));const [text,setText]=useState('');const [name,setName]=useState('');const [url,setUrl]=useState('');const [category,setCategory]=useState('Home & living');const [unit,setUnit]=useState('piece');const [booking,setBooking]=useState('100');const [closeAt,setCloseAt]=useState('');const [check,setCheck]=useState(false);const [check2,setCheck2]=useState(false);const [check3,setCheck3]=useState(false);const [fail,setFail]=useState(false);const [area,setArea]=useState(state.area);const [pincode,setPincode]=useState(state.pincode);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>previous?.focus();},[]);
 const titles:Record<string,string>={join:'A small booking. Your choice stays yours.',offer:'Your offer. Your decision.',pay:'One clear total.',bid:'Your price. Kept private.',pricing:'Set a price you can stand behind.',dispatch:'Good progress needs proof.',checks:'Take a moment. Check your order.',handover:'Confirm the handover.',settle:'Ready to close the loop?',wave:'Your seller’s Wave, reconciled.',leave:'Your choice comes first.',issue:'Let’s get this sorted.',resolve:'Resolve the issue with context.',identify:'Found something you want?',create:'Start something together.',location:'Where are you pooling?',notifications:'Your POOL, as it happens.',tour:'One purchase. Every perspective.',reset:'Start a fresh walkthrough?',disclosure:'A finished experience. An honest prototype.',document:'Your example order record',warranty:'Your accepted example terms'};
 const decimal=(s:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('Enter an amount with at most two decimal places.');const result=Math.round(Number(s)*100);if(!Number.isSafeInteger(result)||result<=0)throw Error('Enter a positive valid amount.');return result;};
 const apply=(action:Parameters<typeof act>[1],fields:Partial<Journey>={})=>{if(act(p.id,action,fields)){close();return true;}setError('The action could not be completed. Check the requirements and notification.');return false;};
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{
  if(kind==='join'){if(!check)throw Error('Please review the refundable booking terms.');const base=Number(qty)*p.scale;if(apply('join',{qty:base,needBy:date,address}))go('pool/'+p.id);}
  if(kind==='offer'){if(!check)throw Error('Please review and accept the offer terms.');if(apply('accept',{plan}))go('order/'+p.id);}
  if(kind==='pay'){setBusy(true);await new Promise(r=>setTimeout(r,450));setBusy(false);if(fail){setError('Example payment declined. Nothing was captured. Choose another method and retry.');return;}if(apply('pay',{payment:method}))go('order/'+p.id);}
  if(kind==='bid'){if(!check)throw Error('Confirm that your all-in price is guaranteed.');apply('bid',{sellerBid:decimal(amount),capacity:Number(capacity)});}
  if(kind==='pricing'){if(!check)throw Error('Review capacity, delivery and the example terms before publishing.');apply('publish',{buyerPrice:decimal(amount)});}
  if(kind==='dispatch')apply('dispatch',{proof:text});
  if(kind==='checks'){if(!check||!check2||!check3)throw Error('Complete each required check, or report an issue instead.');apply('check');}
  if(kind==='handover')apply('handover',{code:text});
  if(kind==='settle'){if(!check||!check2)throw Error('Both review confirmations are required.');apply('settle',{reviewed:true});}
  if(kind==='wave')apply('wave');
  if(kind==='leave')apply('leave');
  if(kind==='issue')apply('issue',{issue:text});
  if(kind==='resolve'){if(text.trim().length<10)throw Error('Write a resolution note of at least 10 characters.');if(act(p.id,'resolve')){setState(s=>({...s,journeys:{...s.journeys,[p.id]:{...s.journeys[p.id],events:[...s.journeys[p.id].events,'Resolution note: '+text.trim()]}}}));close();}}
  if(kind==='location'){if(!area.trim()||!/^\d{6}$/.test(pincode))throw Error('Enter an area and a six-digit Indian pincode.');setState(s=>({...s,area:area.trim(),pincode}));close();}
  if(kind==='reset'){setState(()=>initialPresentation());switchRole('buyer');close();toast('Presentation reset. Your next walkthrough is ready.');}
  if(kind==='identify'){if(url){const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error('Use a public http or https product link without login details.');}if(!name.trim())throw Error('Confirm the exact product name. We won’t infer it from an unverified link.');const existing=state.products.find(x=>x.name.toLowerCase().includes(name.trim().toLowerCase()));if(existing){close();go('pool/'+existing.id);}else{setState(s=>({...s,notices:[`Product request saved locally: ${name.trim()}${url?' · '+new URL(url).hostname:''}. Identity unconfirmed.`,...s.notices]}));modal({kind:'create'});toast('No exact pool match. Enter the confirmed details to start an example pool.');}}
  if(kind==='create'){if(name.trim().length<3)throw Error('Enter the exact product or grouping name.');if(!closeAt)throw Error('Choose when this pool closes. No closing time is preselected.');const closeMs=Date.parse(closeAt);if(!Number.isFinite(closeMs)||closeMs<=Date.now())throw Error('Choose a future closing time.');if(!date||Date.parse(date+'T23:59:59')<=closeMs)throw Error('Your need-by date must follow the pool’s closing time.');const reference=decimal(amount),bookingMinor=decimal(booking);if(bookingMinor>reference)throw Error('Example booking cannot exceed the indicative unit budget.');const id='custom-'+Date.now().toString(36);const created:Product={id,name:name.trim(),category,description:'Buyer-described example product. Identity and specifications remain unconfirmed until reviewed.',variant:'Buyer-described configuration · unconfirmed',art:category==='Electronics'?0:category==='Appliances'?1:category==='Food & essentials'?3:2,unit,scale:unit==='kg'?1000:1,min:unit==='kg'?500:1,step:unit==='kg'?250:1,booking:bookingMinor,reference,sellerPrice:reference,buyerPrice:reference,delivery:'Fulfilment terms require seller confirmation',warranty:'Warranty or quality terms require seller confirmation',returnCost:0,steps:['Fulfilment proof','Buyer checks','Handover code']};setState(s=>({...s,products:[created,...s.products],journeys:{...s.journeys,[id]:{...initialJourney(created),closeAt,needBy:date}},notices:[`Example pool created: ${created.name}. Seller terms still need confirmation.`,...s.notices]}));close();go('pool/'+id);}
 }catch(e){setError(e instanceof Error?e.message:'Please check your entries.');}};
 const checkbox=(label:string,value:boolean,set:(b:boolean)=>void)=><label className="check-field"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><span>{label}</span></label>;
 const transaction=['join','offer','pay','bid','pricing','dispatch','checks','handover','settle','wave','leave','issue','resolve'].includes(kind);
 return <dialog ref={ref} className={`app-dialog ${['tour','disclosure'].includes(kind)?'wide':''}`} onCancel={close} onClick={e=>{if(e.target===ref.current)close();}} aria-labelledby="dialog-title"><form onSubmit={submit}><div className="dialog-header"><span className="eyebrow">{['bid','pricing'].includes(kind)?'PRIVATE WORKSPACE':'POOL · PRESENTATION'}</span><button type="button" className="icon-button" onClick={close} aria-label="Close dialog"><Icon name="close"/></button></div><h2 id="dialog-title">{titles[kind]??'Your POOL'}</h2>
 {transaction&&<div className="dialog-product"><Art index={p.art}/><div><strong>{p.name}</strong><small>{p.variant}</small></div></div>}
 {kind==='join'&&<><p>Pay a refundable booking to confirm your interest. Review the final price after sellers bid. You can still walk away.</p><div className="form-columns"><label className="field"><span>Quantity ({p.unit})</span><input type="number" required min={p.min/p.scale} step={p.step/p.scale} value={qty} onChange={e=>setQty(e.target.value)}/></label><label className="field"><span>I need it by</span><input required type="date" min={j.closeAt.slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label></div><label className="field"><span>Delivery / pickup area</span><textarea value={address} required onChange={e=>setAddress(e.target.value)}/></label><div className="receipt"><div><span>Refundable example booking</span><strong>{money(p.booking)}</strong></div><div><span>Final product price</span><strong>After bidding</strong></div></div>{checkbox('I understand this is a refundable example booking, not a commitment to accept the final offer.',check,setCheck)}<div className="info-note">No UPI request or real charge is created.</div></>}
 {kind==='offer'&&<><Badge>Seller A · reviewed in this example</Badge><div className="offer-amount"><small>Your guaranteed all-in price</small><strong>{money(n.total)}</strong><span>{j.qty/p.scale} {p.unit} · {p.delivery}</span></div><div className="receipt"><div><span>Booking credit</span><strong>−{money(j.bookingPaid)}</strong></div><div className="total"><span>Remaining balance</span><strong>{money(n.balance)}</strong></div><div><span>Warranty / quality</span><strong>{p.warranty}</strong></div><div><span>Before-dispatch cancellation</span><strong>Free</strong></div><div><span>Disclosed maximum later return cost</span><strong>{money(p.returnCost)}</strong></div></div><fieldset className="choices"><legend>Choose your payment plan</legend><label className={plan==='full'?'chosen':''}><input type="radio" name="plan" checked={plan==='full'} onChange={()=>setPlan('full')}/><span><strong>Pay the balance now</strong><small>Complete payment before dispatch.</small></span></label><label className={plan==='handover'?'chosen':''}><input type="radio" name="plan" checked={plan==='handover'} onChange={()=>setPlan('handover')}/><span><strong>Pay the balance at handover</strong><small>UPI or card after checks, before the code. No cash.</small></span></label></fieldset>{checkbox('I reviewed my price, quantity, need-by date and example fulfilment terms.',check,setCheck)}<div className="info-note">Wave Drop is separate and not guaranteed. This example does not represent verified GST invoice treatment.</div></>}
 {kind==='pay'&&<><div className="offer-amount"><small>Balance to pay · simulated</small><strong>{money(n.balance)}</strong><span>Your {money(j.bookingPaid)} booking is already credited.</span></div><fieldset className="choices"><legend>Payment method</legend>{(['UPI','Card'] as const).map(m=><label key={m} className={method===m?'chosen':''}><input name="payment" type="radio" checked={method===m} onChange={()=>setMethod(m)}/><span><strong>{m==='UPI'?'UPI':'Debit / credit card'}</strong><small>Presentation method · no account details required</small></span><Icon name="wallet"/></label>)}</fieldset><details className="demo-controls"><summary>Presentation controls</summary>{checkbox('Demonstrate a declined payment',fail,setFail)}</details><div className="info-note">In the intended flow, your licensed payment provider holds the money until handover. This button only advances the local example.</div></>}
 {kind==='bid'&&<><p>Only you and authorized POOL operations can see this bid in the intended product. Other sellers cannot see your price.</p><div className="form-columns"><label className="field"><span>Your all-in price per {p.unit} (₹)</span><input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>Capacity ({p.unit})</span><input required type="number" min="1" step="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label></div><div className="receipt"><div><span>Buyer need-by</span><strong>{j.needBy}</strong></div><div><span>Covered fulfilment</span><strong>{p.delivery}</strong></div><div><span>Example accepted Wave slabs</span><strong>1–9: ₹0 · 10–24: ₹300 · 25+: ₹700</strong></div></div><p className="caption">The Wave slabs illustrate this presentation and are not a fixed POOL policy. Only offer slabs your own margin supports.</p>{checkbox('My all-in price covers the displayed terms and remains valid even if only one buyer completes.',check,setCheck)}</>}
 {kind==='pricing'&&<><Badge tone="gray"><Icon name="lock" size={13}/> Sealed bid access recorded locally</Badge><div className="receipt"><div><span>Seller A · all-in per {p.unit}</span><strong>{money(j.sellerBid)}</strong></div><div><span>Quantity to assign</span><strong>{j.qty/p.scale} of {j.capacity} {p.unit}</strong></div><div><span>Example outside reference</span><strong>{money(p.reference)} · not fetched</strong></div><div><span>Assignment</span><strong>1 buyer → Seller A</strong></div></div><label className="field"><span>Buyer price per {p.unit} (₹)</span><input required type="number" min={j.sellerBid/100} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="pricing-difference"><span>POOL price difference per {p.unit}</span><strong>{Number.isFinite(Number(amount))?money(Math.round(Number(amount)*100)-j.sellerBid):'—'}</strong></div><p className="caption">No fixed fee. The difference is not pure profit: commission GST and applicable withholdings require reviewed treatment. Capacity-split pools need one priced assignment per covering bid; this walkthrough has one buyer.</p>{checkbox('I reviewed capacity, need-by, quantity and fulfilment coverage for this example assignment.',check,setCheck)}</>}
 {kind==='dispatch'&&<><p>Record the fulfilment evidence required by the accepted profile: {p.steps.join(', ')}.</p><label className="field"><span>Example dispatch / preparation proof reference</span><input required minLength={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Example dispatch record 001"/></label><p className="caption">This records a local example reference. It does not upload or verify a real photo or courier event.</p></>}
 {kind==='checks'&&<><p>Complete your checks in person before giving the seller your one-time code.</p>{checkbox('The product or prepared order matches the accepted specification and quantity.',check,setCheck)}{checkbox('The condition and the profile’s required checks are satisfactory.',check2,setCheck2)}{checkbox('The full payment is captured and I am ready to accept handover.',check3,setCheck3)}<Button type="button" kind="secondary" onClick={()=>modal({kind:'issue',id:p.id})}>Something isn’t right · report an issue</Button></>}
 {kind==='handover'&&<><p>Ask the buyer for the code only after their checks and full payment are complete.</p><label className="field"><span>6-digit example order code</span><input className="code-input" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={text} onChange={e=>setText(e.target.value)} placeholder="Enter buyer’s code" autoComplete="off"/></label><p className="caption">This is a presentation code, not a secure production credential. The backend’s hashed, expiring code flow will replace it.</p></>}
 {kind==='settle'&&<><p>Advance the presentation only after checking the accepted fulfilment profile.</p>{checkbox('All required proof, including any installation or service evidence, is complete in this example.',check,setCheck)}{checkbox('Advance past the example return window; there is no open issue or return.',check2,setCheck2)}<div className="info-note">This explicitly advances the presentation timeline. It does not change real deadlines or execute a seller payout.</div></>}
 {kind==='wave'&&<><div className="receipt"><div><span>Assigned seller</span><strong>Seller A</strong></div><div><span>Eligible settled buyers in this session</span><strong>1</strong></div><div><span>First contributing example slab</span><strong>10th settled buyer</strong></div><div className="total"><span>Your calculated Wave refund</span><strong>₹0</strong></div></div><p>No refund is invented. Use the separate Wave calculator to demonstrate larger settled groups.</p></>}
 {kind==='leave'&&<><div className="offer-amount"><small>Full refund recorded · simulated</small><strong>{money(j.captured)}</strong></div><p>{['joined','bid','offer'].includes(j.stage)?'You’re free to walk away. Your booking goes back to its original method.':'This order has not been dispatched. Cancellation has no charge.'}</p><div className="info-note">This example records the refund immediately. Real refund timing depends on the payment provider; no completion date is promised here.</div></>}
 {kind==='issue'&&<><p>Tell us what happened. This creates a local issue and blocks handover and settlement until the POOL team reviews it.</p><label className="field"><span>What needs attention?</span><textarea required minLength={5} value={text} onChange={e=>setText(e.target.value)} placeholder="Wrong item, damage, delay, installation or another concern…"/></label><p className="caption">Do not include sensitive information. This example stays on your device and is not sent to support.</p></>}
 {kind==='resolve'&&<><div className="alert compact"><Icon name="help"/><p>{j.issue}</p></div><label className="field"><span>Resolution note</span><textarea required minLength={10} value={text} onChange={e=>setText(e.target.value)} placeholder="Explain how the issue was reviewed and resolved in the scenario."/></label><p>This clears the example issue hold. A real defect return or compensation needs the applicable reviewed policy; no automatic refund is implied.</p></>}
 {kind==='identify'&&<><p>Start with a link or the exact product name. Confirm the details so the group buys the right thing.</p><label className="field"><span>Product link (optional)</span><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label className="field"><span>Exact product or grouping name</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="For example: 55-inch 4K television"/></label><div className="evidence-box"><Icon name="search"/><div><strong>Product identity: unconfirmed</strong><p>No page is fetched in this prototype. We do not claim an AI match or invent specifications. Amazon and Flipkart links are not scraped.</p></div></div><p className="caption">A matching example pool opens if the name matches. Otherwise you can describe a new pool.</p></>}
 {kind==='create'&&<><p>Define the need. Choose the closing time. The final offer comes after seller bidding.</p><label className="field"><span>Exact product or grouping</span><input required minLength={3} value={name} onChange={e=>setName(e.target.value)} placeholder="What would you like to buy together?"/></label><div className="form-columns"><label className="field"><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}>{['Electronics','Appliances','Home & living','Food & essentials','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Unit of measure</span><select value={unit} onChange={e=>setUnit(e.target.value)}>{['piece','kg','pack','metre','litre','hour'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="form-columns"><label className="field"><span>Choose closing time (your local time)</span><input type="datetime-local" required value={closeAt} onChange={e=>setCloseAt(e.target.value)}/></label><label className="field"><span>I need it by</span><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="form-columns"><label className="field"><span>Indicative unit budget (₹)</span><input required type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>Example refundable booking (₹)</span><input required type="number" min="1" step="0.01" value={booking} onChange={e=>setBooking(e.target.value)}/></label></div><div className="info-note">Example pool only. The budget is not a seller quote. Product identity, taxes and seller fulfilment terms still require review.</div></>}
 {kind==='location'&&<><p>Keep nearby pools relevant. No location permission is needed.</p><label className="field"><span>Area and city</span><input required value={area} onChange={e=>setArea(e.target.value)}/></label><label className="field"><span>Indian pincode</span><input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={pincode} onChange={e=>setPincode(e.target.value)}/></label><p className="caption">Changing this display preference does not verify seller serviceability or change existing accepted order addresses.</p></>}
 {kind==='notifications'&&<div className="notification-list">{state.notices.length?state.notices.map((s,i)=><div key={i}><Icon name="bell" size={18}/><p>{s}</p></div>):<p>No activity yet. As you move through a purchase, updates appear here.</p>}</div>}
 {kind==='tour'&&<><p>Walk through the business from each side. Your actions stay connected across all three workspaces.</p><div className="tour-grid">{[['buyer','users','01','Choose & book','Explore a product, choose quantity and need-by, then place a refundable example booking.'],['seller','store','02','Bid privately','Use the seller workspace to submit a covering all-in price and capacity.'],['ops','settings','03','Price & publish','The POOL team reviews the bid and decides the buyer’s price.']] .map(([role,icon,num,title,description])=><button key={role} type="button" onClick={()=>{switchRole(role as 'buyer'|'seller'|'ops');close();}}><Icon name={icon} size={26}/><small>{num}</small><strong>{title}</strong><p>{description}</p><span>Open workspace <Icon name="arrow" size={15}/></span></button>)}</div><div className="tour-path"><span>Buyer accepts or walks away</span><Icon name="chevron" size={15}/><span>Payment</span><Icon name="chevron" size={15}/><span>Proof & handover</span><Icon name="chevron" size={15}/><span>Issue review</span><Icon name="chevron" size={15}/><span>Settlement & Wave</span></div><p className="caption">Presentation controls explicitly advance the timeline. No fake live countdowns, real customers or actual payment success are claimed.</p></>}
 {kind==='disclosure'&&<><p>This is POOL’s connected frontend presentation, built from the founder’s current India-first decisions.</p><div className="disclosure-grid"><section><Icon name="check"/><h3>You can try</h3><p>Buyer discovery, booking, offer decisions, full or handover payment, seller bids, team pricing, fulfilment evidence, handover checks, issue resolution, settlement, documents and Wave explanations.</p></section><section><Icon name="lock"/><h3>Clearly illustrative</h3><p>Products, prices, seller identities, payment receipts and financial activity are examples stored on this browser. Product images are generated, unbranded illustrations. Workspace switching is not authentication.</p></section><section><Icon name="settings"/><h3>Before a real launch</h3><p>Verified product data, secure sign-in, payment-provider integration, real document and proof handling, full translations, tax/legal review, operational controls and production quality gates are still required.</p></section></div></>}
 {kind==='reset'&&<p>This removes the current presentation’s local orders, bids, saved products and activity. It does not change the PostgreSQL database or any other browser data.</p>}
 {['document','warranty'].includes(kind)&&<><Badge tone="amber">EXAMPLE · NOT A TAX INVOICE OR REAL WARRANTY</Badge><div className="receipt"><div><span>Order</span><strong>POOL-{p.id.toUpperCase()}</strong></div><div><span>Product</span><strong>{p.name}</strong></div><div><span>Quantity</span><strong>{j.qty/p.scale} {p.unit}</strong></div><div><span>Example all-in total</span><strong>{money(n.total)}</strong></div><div><span>Captured in scenario</span><strong>{money(j.captured)}</strong></div><div><span>Warranty / quality</span><strong>{p.warranty}</strong></div><div><span>Fulfilment evidence reference</span><strong>{j.proof||'Not yet recorded'}</strong></div></div><Button type="button" kind="secondary" onClick={()=>{const content=`POOL PRESENTATION — EXAMPLE ONLY\nNot a tax invoice or real warranty\nProduct: ${p.name}\nQuantity: ${j.qty/p.scale} ${p.unit}\nTotal: ${money(n.total)}\nCaptured (simulated): ${money(j.captured)}\nTerms: ${p.warranty}\nProof reference: ${j.proof}\n`;const link=document.createElement('a');const object=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));link.href=object;link.download=`POOL-example-${p.id}.txt`;link.click();URL.revokeObjectURL(object);}}>Download example record <Icon name="file" size={16}/></Button></>}
 {error&&<div role="alert" className="form-error">{error}</div>}
 {!['tour','disclosure','notifications','document','warranty'].includes(kind)&&<div className={`dialog-actions ${kind==='offer'?'equal':''}`}><Button type="button" kind="secondary" onClick={kind==='offer'?()=>modal({kind:'leave',id:p.id}):close}>{kind==='offer'?'Walk away & refund booking':kind==='leave'?'Keep my place':'Back'}</Button><Button type="submit" disabled={busy}>{busy?'Processing example…':({join:'Place example booking',offer:'Accept this offer',pay:'Simulate payment',bid:'Submit sealed bid',pricing:'Publish buyer offer',dispatch:'Record example proof',checks:'Confirm checks & reveal code',handover:'Verify code',settle:'Complete example settlement',wave:'Close example Wave',leave:'Confirm refund & leave',issue:'Create local issue',resolve:'Resolve & release hold',identify:'Find a matching pool',create:'Create example pool',location:'Save area',reset:'Reset presentation'} as Record<string,string>)[kind]??'Continue'}</Button></div>}
 </form></dialog>;
}
