'use client';
import {useEffect,useState,useRef} from 'react';
import {initialPresentation,parsePresentation,transition,type Presentation,type Journey,type Action} from '../lib/presentation';
import {Experience,type Role,type Modal} from './experience-context';
import {Icon} from './ui';
import {Buyer} from './buyer';
import {Workspace} from './workspaces';
import {Dialogs} from './dialogs';
const KEY='pool.presentation.v2';
const navigation:Record<Role,[string,string,string,string,string][]>={buyer:[['discover','grid','Discover','కనుగొనండి','खोजें'],['pools','users','My pools','నా పూల్స్','मेरे पूल'],['orders','box','Orders','ఆర్డర్లు','ऑर्डर'],['wave','wave','Wave Drop','వేవ్ డ్రాప్','वेव ड्रॉप'],['locker','shield','Purchase locker','కొనుగోలు పత్రాలు','खरीद दस्तावेज़'],['saved','heart','Saved','సేవ్ చేసినవి','सेव किए गए']],seller:[['demand','grid','Demand','డిమాండ్','माँग'],['bids','lock','My sealed bids','నా బిడ్లు','मेरी बोलियाँ'],['fulfilment','truck','Fulfilment','డెలివరీ','डिलीवरी'],['payouts','wallet','Payouts','చెల్లింపులు','भुगतान']],ops:[['overview','grid','Overview','అవలోకనం','अवलोकन'],['pricing','settings','Awards & pricing','ధరల నిర్ణయం','आवंटन और कीमत'],['sellers','store','Seller review','విక్రేత సమీక్ష','विक्रेता समीक्षा'],['exceptions','help','Issues & refunds','సమస్యలు','समस्याएँ'],['ledger','wallet','Money & audit','ఖాతాలు','खाता और ऑडिट']]};
export function PoolApp(){
 const [state,update]=useState<Presentation>(initialPresentation);const [ready,setReady]=useState(false);const [role,setRole]=useState<Role>('buyer');const [route,setRoute]=useState('discover');const [modal,setModal]=useState<Modal>(null);const [message,setMessage]=useState('');const [search,setSearch]=useState('');const [mobile,setMobile]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{try{const stored=parsePresentation(localStorage.getItem(KEY));if(stored)update(stored);}catch{}setReady(true);const routeFromHash=()=>{const [r,...v]=location.hash.replace('#/','').split('/');if(['buyer','seller','ops'].includes(r)){setRole(r as Role);setRoute(v.join('/')||navigation[r as Role][0][0]);}};routeFromHash();window.addEventListener('hashchange',routeFromHash);return()=>window.removeEventListener('hashchange',routeFromHash);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(KEY,JSON.stringify(state));}catch{setMessage('Browser storage is unavailable. Changes will last for this visit only.');}document.documentElement.lang=state.language;},[state,ready]);
 const toast=(s:string)=>{setMessage(s);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setMessage(''),4800);};
 const go=(view:string)=>{setRoute(view);location.hash=`/${role}/${view}`;setMobile(false);window.scrollTo({top:0,behavior:'instant'});};
 const switchRole=(r:Role,view?:string)=>{setRole(r);const v=view??navigation[r][0][0];setRoute(v);location.hash=`/${r}/${v}`;setMobile(false);window.scrollTo({top:0,behavior:'instant'});};
 const t=(en:string,te?:string,hi?:string)=>state.language==='te'?te??en:state.language==='hi'?hi??en:en;
 const act=(id:string,action:Action,fields:Partial<Journey>={})=>{try{const p=state.products.find(x=>x.id===id)!;if((action==='bid'||action==='publish')&&!state.sellerApproved)throw Error('Seller review must be approved before bidding or publishing.');const journey=transition(p,state.journeys[id],action,fields);update(s=>({...s,journeys:{...s.journeys,[id]:journey},notices:[`${p.name}: ${journey.events.at(-1)}`,...s.notices].slice(0,30)}));toast(journey.events.at(-1)!);return true;}catch(e){toast(e instanceof Error?e.message:'Action could not be completed.');return false;}};
 const entries=navigation[role];const title=entries.find(x=>x[0]===route)?.[2]??(route==='help'?'Help & support':route==='settings'?'Your preferences':'Your POOL');
 const context={state,role,route,setState:update,go,switchRole,modal:setModal,act,toast,t,product:(id:string)=>state.products.find(p=>p.id===id)??state.products[0]};
 return <Experience.Provider value={context}>
 <a href="#content" className="skip-link">Skip to content</a>
 <div className="presentation-bar"><span><i/> {t('Presentation mode','ప్రెజెంటేషన్ మోడ్','प्रस्तुति मोड')} <span className="bar-detail">· {t('Illustrative products & transactions. No money moves.','ఉదాహరణ వస్తువులు, లావాదేవీలు. డబ్బు చెల్లించబడదు.','उदाहरण प्रोडक्ट और लेनदेन। कोई वास्तविक भुगतान नहीं।')}</span></span><button onClick={()=>setModal({kind:'tour'})}>{t('Explore the full journey','పూర్తి ప్రయాణం చూడండి','पूरा सफर देखें')} <Icon name="arrow" size={14}/></button></div>
 <div className="app-frame"><aside className={`sidebar ${mobile?'mobile-open':''}`}><a className="wordmark" href="#/buyer/discover" onClick={()=>switchRole('buyer')} aria-label="POOL home">p<span className="linked-o">oo</span>l<span className="brand-stop">.</span></a><div className="workspace-label">{t('YOUR WORKSPACE','మీ వర్క్‌స్పేస్','आपका वर्कस्पेस')}</div><label className="role-select"><Icon name={role==='buyer'?'users':role==='seller'?'store':'settings'}/><select aria-label="Presentation workspace" value={role} onChange={e=>switchRole(e.target.value as Role)}><option value="buyer">Buyer experience</option><option value="seller">Seller workspace</option><option value="ops">POOL operations</option></select></label><nav aria-label="Workspace navigation">{entries.map(([path,icon,en,te,hi])=><button key={path} onClick={()=>go(path)} className={`nav-item ${route===path?'active':''}`}><Icon name={icon}/><span>{t(en,te,hi)}</span>{path==='pools'&&Object.values(state.journeys).filter(j=>j.stage!=='open').length>0&&<b>{Object.values(state.journeys).filter(j=>j.stage!=='open').length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-story"><Icon name="wave" size={28}/><strong>{t('Good things happen together.','కలిసి మంచి సాధిద్దాం.','साथ में बेहतर।')}</strong><p>{t('Your price is yours. Extra savings are shared.','మీ ధర మీదే. అదనపు పొదుపు అందరిదీ.','आपकी कीमत तय। अतिरिक्त बचत साझा।')}</p><button onClick={()=>switchRole('buyer','wave')}>Discover Wave Drop <Icon name="chevron" size={14}/></button></div><button className={`nav-item ${route==='help'?'active':''}`} onClick={()=>go('help')}><Icon name="help"/>{t('Help & support','సహాయం','सहायता')}</button><button className="profile-button" onClick={()=>go('settings')}><span className="avatar">{role==='buyer'?'AK':role==='seller'?'S':'P'}</span><span><strong>{role==='buyer'?'Aarav K.':role==='seller'?'Seller A':'POOL team'}</strong><small>Example {role} profile</small></span><Icon name="settings" size={17}/></button></div></aside>
 <div className="app-main"><header className="topbar"><button className="icon-button mobile-toggle" aria-label="Open navigation" onClick={()=>setMobile(!mobile)}><Icon name="grid"/></button><button className="location" onClick={()=>setModal({kind:'location'})}><Icon name="pin" size={18}/><span><small>{t('Shopping in','షాపింగ్ ప్రాంతం','खरीदारी का इलाका')}</small><strong>{state.area}</strong></span><Icon name="down" size={14}/></button><form className="top-search" onSubmit={e=>{e.preventDefault();go('discover');}}><Icon name="search" size={18}/><input aria-label="Search products" placeholder={t('Search anything you want to pool','మీకు కావాల్సింది వెతకండి','जो खरीदना है खोजें')} value={search} onChange={e=>{setSearch(e.target.value);if(role==='buyer'&&route!=='discover')go('discover');}}/><kbd>⌕</kbd></form><label className="locale"><select aria-label="Language" value={state.language} onChange={e=>update(s=>({...s,language:e.target.value as Presentation['language']}))}><option value="en">English</option><option value="te">తెలుగు</option><option value="hi">हिन्दी</option></select></label><button className="icon-button notification-button" aria-label="Notifications" onClick={()=>setModal({kind:'notifications'})}><Icon name="bell"/>{state.notices.length>0&&<i/>}</button></header>
 <main id="content" tabIndex={-1}>{role==='buyer'?<Buyer search={search} setSearch={setSearch}/>:<Workspace title={title}/>}</main><footer className="app-footer"><span>POOL · Before you buy it, POOL it.</span><button onClick={()=>setModal({kind:'disclosure'})}>About this presentation</button><span>India · INR</span></footer></div></div>
 <nav className="mobile-dock" aria-label="Mobile navigation">{entries.slice(0,4).map(([path,icon,en,te,hi])=><button key={path} className={route===path?'active':''} onClick={()=>go(path)}><Icon name={icon}/><span>{t(en,te,hi)}</span></button>)}</nav>
 {message&&<div className="toast" role="status"><Icon name="bell" size={18}/>{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}><Icon name="close" size={16}/></button></div>}
 <Dialogs value={modal} close={()=>setModal(null)}/></Experience.Provider>;
}
