/** Explicitly local presentation scenarios, never payment-provider or database facts.
 * All example terms live here as data. No production engine policy is changed.
 */
export type Stage = 'open' | 'joined' | 'bid' | 'offer' | 'accepted' | 'paid' | 'dispatched' | 'delivered' | 'settled' | 'refunded';
export type Product = { id:string; name:string; category:string; description:string; variant:string; art:number; unit:string; scale:number; min:number; step:number; booking:number; reference:number; sellerPrice:number; buyerPrice:number; delivery:string; warranty:string; returnCost:number; steps:string[] };
export type Journey = { stage:Stage; qty:number; bookingPaid:number; captured:number; refund:number; sellerBid:number; buyerPrice:number; capacity:number; plan:'full'|'handover'; payment:'UPI'|'Card'; needBy:string; closeAt:string; address:string; issue:string; checks:boolean; code:string; proof:string; reviewed:boolean; waveClosed:boolean; waveRefund:number; events:string[] };
export type Presentation = { version:2; products:Product[]; journeys:Record<string,Journey>; saved:string[]; notices:string[]; area:string; pincode:string; language:'en'|'te'|'hi'; sellerApproved:boolean };
export const money = (paise:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:paise%100 ? 2:0}).format(paise/100);
export const products:Product[] = [
 {id:'tv',name:'55-inch 4K television',category:'Electronics',description:'A cinema night, without the cinema queue. A 55-inch screen with the exact specifications confirmed before an offer.',variant:'55 inch · 4K · Graphite',art:0,unit:'piece',scale:1,min:1,step:1,booking:200000,reference:4500000,sellerPrice:4000000,buyerPrice:4300000,delivery:'Home delivery + installation',warranty:'12-month seller-provided warranty in this example',returnCost:50000,steps:['Dispatch record','Open-box check','Handover code','Installation record'],},
 {id:'wash',name:'8 kg front-load washer',category:'Appliances',description:'A quieter laundry day. One exact configuration, one all-in offer, with delivery and installation together.',variant:'8 kg · Front load · Silver',art:1,unit:'piece',scale:1,min:1,step:1,booking:150000,reference:3800000,sellerPrice:3200000,buyerPrice:3450000,delivery:'Home delivery + installation',warranty:'24-month seller-provided warranty in this example',returnCost:50000,steps:['Dispatch record','Open-box check','Handover code','Installation record']},
 {id:'chair',name:'Oak everyday chair',category:'Home & living',description:'For the dinner table, the study or the café. Choose the quantity you need; the seller covers the complete order.',variant:'Solid oak · Natural · Fabric seat',art:2,unit:'piece',scale:1,min:1,step:1,booking:30000,reference:750000,sellerPrice:580000,buyerPrice:650000,delivery:'Scheduled home delivery',warranty:'12-month seller-provided warranty in this example',returnCost:20000,steps:['Dispatch record','Condition check','Handover code']},
 {id:'coffee',name:'Everyday filter coffee',category:'Food & essentials',description:'The morning ritual, pooled. Roast, blend and pack details are agreed as part of this product’s terms.',variant:'Filter grind · Medium roast',art:3,unit:'kg',scale:1000,min:500,step:250,booking:10000,reference:120000,sellerPrice:85000,buyerPrice:100000,delivery:'Scheduled neighbourhood pickup',warranty:'Quality issue review under the accepted food profile',returnCost:0,steps:['Batch preparation record','Pack check','Pickup code']},
];
export function initialJourney(p:Product):Journey {return {stage:'open',qty:p.min,bookingPaid:0,captured:0,refund:0,sellerBid:p.sellerPrice,buyerPrice:p.buyerPrice,capacity:100,plan:'full',payment:'UPI',needBy:'2026-10-18',closeAt:'2026-10-08T18:00',address:'Example home · Kondapur, Hyderabad · 500084',issue:'',checks:false,code:'482716',proof:'',reviewed:false,waveClosed:false,waveRefund:0,events:[]};}
export function initialPresentation():Presentation {return {version:2,products,journeys:Object.fromEntries(products.map(p=>[p.id,initialJourney(p)])),saved:[],notices:[],area:'Kondapur, Hyderabad',pincode:'500084',language:'en',sellerApproved:true};}
export function line(price:number,qty:number,scale:number){const n=BigInt(price)*BigInt(qty);return Number((n+BigInt(Math.floor(scale/2)))/BigInt(scale));}
export function totals(p:Product,j:Journey){const total=line(j.buyerPrice,j.qty,p.scale);const seller=line(j.sellerBid,j.qty,p.scale);return {total,seller,margin:total-seller,balance:Math.max(0,total-j.captured),booking:Math.min(p.booking,total),held:Math.max(0,j.captured-j.refund-j.waveRefund)};}
// Scenario slabs: positions 1–9 add 0; 10–24 add ₹300; 25 onward add ₹700.
// This illustrates the founder's separate seller pot. Never a promised discount.
export function waveExample(count:number){if(!Number.isSafeInteger(count)||count<0||count>1000)throw Error('Invalid settled count');const pot=Math.max(0,Math.min(count,24)-9)*30000+Math.max(0,count-24)*70000;const each=count?Math.floor(pot/count):0;return {pot,each,remainder:count?pot%count:0,held:count*70000};}
export type Action = 'join'|'bid'|'publish'|'accept'|'pay'|'dispatch'|'check'|'handover'|'settle'|'wave'|'leave'|'issue'|'resolve';
export function transition(p:Product,j:Journey,action:Action,fields:Partial<Journey>={}):Journey {
 const next={...j};let event='';const requireStage=(...stages:Stage[])=>{if(!stages.includes(j.stage))throw Error('This action is not available at the current step.');};
 if(action==='join') {requireStage('open');const qty=fields.qty??p.min;if(!Number.isSafeInteger(qty)||qty<p.min||(qty-p.min)%p.step!==0||qty>p.scale*1000)throw Error('Choose a valid quantity.');if(!fields.needBy||fields.needBy<j.closeAt.slice(0,10))throw Error('Choose a need-by date after the pool closes.');next.qty=qty;next.needBy=fields.needBy;next.address=fields.address?.trim()||j.address;next.bookingPaid=Math.min(p.booking,line(j.buyerPrice,qty,p.scale));next.captured=next.bookingPaid;next.stage='joined';event='Buyer placed a refundable booking (simulated).';}
 if(action==='bid'){requireStage('joined','bid');const bid=fields.sellerBid??j.sellerBid;const capacity=fields.capacity??j.capacity;if(!Number.isSafeInteger(bid)||bid<=0)throw Error('Enter a positive price with at most two decimal places.');if(!Number.isSafeInteger(capacity)||capacity<Math.ceil(j.qty/p.scale))throw Error('Capacity must cover this buyer’s quantity.');if(j.stage==='bid'&&bid>j.sellerBid)throw Error('A bid revision can only lower the price.');next.sellerBid=bid;next.capacity=capacity;next.stage='bid';event='Seller submitted a sealed, guaranteed bid (simulated).';}
 if(action==='publish'){requireStage('bid');const price=fields.buyerPrice??j.buyerPrice;if(!Number.isSafeInteger(price)||price<j.sellerBid)throw Error('Buyer price must cover the seller price.');next.buyerPrice=price;next.stage='offer';event='POOL team recorded the buyer price and published the offer.';}
 if(action==='accept'){requireStage('offer');next.plan=fields.plan??'full';next.stage='accepted';event='Buyer accepted their price and terms.';}
 if(action==='pay'){requireStage('accepted','dispatched');next.captured=totals(p,j).total;next.payment=fields.payment??'UPI';if(j.stage==='accepted')next.stage='paid';event='Remaining balance captured in the presentation scenario.';}
 if(action==='dispatch'){requireStage('paid','accepted');if(j.stage==='accepted'&&j.plan!=='handover')throw Error('This order requires full payment before dispatch.');if(!fields.proof?.trim())throw Error('Add a dispatch or preparation proof reference.');next.proof=fields.proof.trim();next.stage='dispatched';event='Seller recorded fulfilment proof: '+next.proof;}
 if(action==='check'){requireStage('dispatched');if(j.issue)throw Error('Resolve the open issue before handover.');if(totals(p,j).balance>0)throw Error('Complete the balance payment before handover.');next.checks=true;event='Buyer confirmed the required handover checks.';}
 if(action==='handover'){requireStage('dispatched');if(j.issue||!j.checks||totals(p,j).balance>0)throw Error('Payment, handover checks and issue resolution must be complete.');if(fields.code!==j.code)throw Error('That code does not match this example order.');next.stage='delivered';event='Seller verified the order-bound handover code (simulated).';}
 if(action==='settle'){requireStage('delivered');if(j.issue)throw Error('An open issue blocks settlement.');if(!fields.reviewed)throw Error('Confirm all proof and the example return window are complete.');next.reviewed=true;next.stage='settled';event='Example proof and return-window review completed; order settled.';}
 if(action==='wave'){requireStage('settled');if(j.issue||j.waveClosed)throw Error('Wave is already closed or an issue is open.');next.waveClosed=true;next.waveRefund=0;event='Seller Wave closed: 1 settled buyer is below the first slab; refund ₹0. See the separate 25-buyer illustration in Wave Drop.';}
 if(action==='leave'){requireStage('joined','bid','offer','accepted','paid');next.refund=j.captured;next.stage='refunded';event='Full captured amount marked for return to original method (simulated).';}
 if(action==='issue'){if(j.stage==='open'||j.stage==='refunded')throw Error('Join a pool before opening an order issue.');if(!fields.issue?.trim())throw Error('Tell us what needs attention.');if(j.waveClosed)throw Error('This completed scenario requires a new support review.');next.issue=fields.issue.trim();event='Buyer opened an issue. Handover and settlement are blocked.';}
 if(action==='resolve'){if(!j.issue)throw Error('No issue is open.');next.issue='';event='POOL operations resolved the issue in the presentation scenario.';}
 return {...next,events:[...j.events,event]};
}
export function parsePresentation(raw:string|null):Presentation|null {try{const v=JSON.parse(raw??'null');if(v?.version!==2||!Array.isArray(v.products)||!v.products.length||!v.journeys||!Array.isArray(v.saved)||!Array.isArray(v.notices))return null;for(const p of v.products){const j=v.journeys[p.id];if(!j||!['open','joined','bid','offer','accepted','paid','dispatched','delivered','settled','refunded'].includes(j.stage)||!Number.isSafeInteger(j.qty)||!Array.isArray(j.events)||typeof p.name!=='string')return null;}return v;}catch{return null;}}
